name: CI Pipeline
on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
          #- macos-13
        dc:
          - dmd-2.098.1
          - dmd-2.111.0
          - ldc-1.28.1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Unit tests
        run: |
          dub build
          dub test
          dub run --root mir-integration-example

      - uses: codecov/codecov-action@v5.1.2

  integration-test:
    name: Integration tests
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        dc:
          - dmd-2.098.1
          - dmd-2.111.0
          - ldc-1.28.1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install influxdb libevent-dev

      - name: Integration tests
        run: |
          sudo service influxdb start
          cd integration
          dub run --build=unittest -c integration
          dub run --build=unittest -c integration-mir
